apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "etlplus-backend.fullname" . }}-config
  labels:
    {{- include "etlplus-backend.labels" . | nindent 4 }}
data:
  config.json: |
{{ toJson .Values.config | indent 4 }}
